worker_processes auto;

events { worker_connections 1024; }

http {
    server {
        listen 443 ssl;
        server_name pay.bharatfinserve.example;

        ssl_certificate     certs/server.crt;
        ssl_certificate_key certs/server.key;

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DES-CBC3-SHA;
        ssl_prefer_server_ciphers on;

        location / { proxy_pass http://payments-svc:8443; }
    }
}
