spring.application.name=payments-svc
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.jks
server.ssl.key-store-type=JKS
server.ssl.enabled-protocols=TLSv1.1,TLSv1.2
server.ssl.ciphers=TLS_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
